#server port
server:
  port: 80
#spring.
spring:
  datasource:
    url: jdbc:mysql:///dbpms?serverTimezone=GMT%2B8&characterEncoding=utf8
    username: root
    password: root
#mybatis
mybatis:
  mapper-locations: classpath:/mapper/*/*.xml
#logging
logging:
  level:
    com.cy: debug
#shiro
shiro:
  loginUrl: /login.html
