#server port
server:
  port: 80
#spring.
spring:
  datasource:
    url: jdbc:mysql:///dbpms?serverTimezone=GMT%2B8&characterEncoding=utf8
    username: root
    password: root
#mybatis
mybatis:
  mapper-locations: classpath:/mapper/*/*.xml
#logging
logging:
  level:
    com.cy: debug
#shiro
shiro:
  # 登录地址
  loginUrl: /login.html
  sessionManager:
    sessionIdCookieEnabled: true
    sessionIdUrlRewritingEnabled: false #不进行url重写（Cookue被禁用以后）
  rememberMeManager:
    cookie:
      maxAge: 3600


